name: CI

on:
  push:
  schedule:
    - cron: '0 12-21/3,0 * * *'

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots
            target/surefire-reports/emailable-report.html

      - name: Attach reports only
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/surefire-reports/emailable-report.html


